### ISSUE TITLE
review

### ISSUE THREAD

**Issue by rostom44** [WildCodeSchool-CDA-LYON-02-2024/React-Form#16]
**Feedback on the website** : I've reviewed your site and wanted to provide some feedback. Overall, it looks impressive, i suggest highlighting more of the code examples (lines or more explication of what we did for the code ) . However, I noticed a few issues that could be improved: [footer disappearing, the GitHub icon not showing up in dark mode because it's black ]. Keep up the good work! i love it"

**Comment by sharmake124** [comment]
Thank you for your feedback, we are going to correct those issues.

**Comment by hamed-cell** [comment]
Hello,

Thank you for your constructive feedback on our website. I'm glad you find the site impressive, and I appreciate your suggestion to highlight more of our code examples. We will consider adding more lines of code and detailed explanations about what we have implemented.

Regarding the issues you've pointed out, thank you for bringing them to my attention. We will address the disappearing footer and ensure that the GitHub icon is visible in dark mode.

As the creator of the site, your feedback is invaluable to us as it helps us continuously improve our site, and we are committed to providing the best user experience possible.

Thank you again for your encouragement and support.
