### ISSUE TITLE
partie technique sur le basic-form 

### ISSUE THREAD

**Issue by HazeFury** [WildCodeSchool-CDA-LYON-02-2024/React-Form#20]
- quand on laisse un input vide après avori cliqué dessus, les bordures deviennent vertes => on s'attend à ce qu'elle soient plutôt rouge pour indiquer qu'il faut remplir le champs

- Il faut mettre des 'I' majuscule au lieu de "i" sur toutes les phrases du genre "i have a handicap"

- je peux sélectionner à la fois le "oui" et le "non" à la question "i have a handicap" => c'est pas normal, il faut que je puisse en sélectionner qu'un seul à la fois

- [détail CSS] les options du select sont trop petites par rapport au reste => il faudrait les agrandir pour harmoniser le tout

**Comment by sharmake124** [comment]
Merci pour votre retour. Nous allons corriger les pépins techniques le plus rapidement possible.
