### ISSUE TITLE
partie technique sur le vectorForm

### ISSUE THREAD

**Issue by HazeFury** [WildCodeSchool-CDA-LYON-02-2024/React-Form#21]
- inputs initialisés avec un espace => en plus du fait qu'il est bizarre de voir un caractère caché dans le champs mot de passe au montage du composant, c'est problématique car l'espace fait partie de la string qui seras envoyé pour se connecter => L'utiolisateur peut chercher longtemps pourquoi il n'arrive pas à se connecter juste parce qu'un espace s'est glissé dans l'input

- un cursoir pointer sur le bouton "submit" ne serait pas de trop

**Comment by sharmake124** [comment]
C'est noté, nous allons corriger les bugs et les erreurs techniques que vous avez signalés. Merci pour votre retour.

**Comment by sharmake124** [comment]
Les problèmes signalés ont été corrigés. Merci.
