### ISSUE TITLE
partie technique sur le basic-form (signup)

### ISSUE THREAD

**Issue by HazeFury** [WildCodeSchool-CDA-LYON-02-2024/React-Form#22]
- quand je copie le code fourni sur la doc ça ne marche pas 

=> à la ligne "<Form onSubmit={(e) => 3.preventDefault()} className="basic-form">" : d'où viens le "3" ??

**Comment by sharmake124** [comment]
Merci pour votre retour. Le numéro 3 est une erreur de frappe de notre côté, nous allons le corriger.

**Comment by sharmake124** [comment]
Nous avons corrigé les erreurs que vous avez signalées
