### ISSUE TITLE
Radio Bug

### ISSUE THREAD

**Issue by Freddyede** [WildCodeSchool-CDA-LYON-02-2024/React-Form#30]
![image](https://github.com/WildCodeSchool-CDA-LYON-02-2024/React-Form/assets/136079691/3f0e804c-30b9-46c6-a08c-6c3251f7b531)
Le principe d'un radio n'est pas de passer de l'un à l'autre facilement et rapidement car sur mon exemple ci-dessus j'ai bel et bien mes deux input radio sélectionner

**Comment by sharmake124** [comment]
fixed
